name: RTDbuild
channels:
 - conda-forge
dependencies:
  - python==3.12
  - sphinx>=4.5.0
  - doxygen>=1.13
  - graphviz>=12.2.1
  - breathe>=4.35
  - exhale>=0.3.7
  - sphinx-rtd-theme>=1.3.0
  - myst-parser>=0.18.1
