# Workflow to 
name: CMake on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Summary
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    
    - name: download armadillo
      shell: bash
      run: |
        wget --no-check-certificate https://sourceforge.net/projects/arma/files/armadillo-12.8.0.tar.xz
        tar xf armadillo-12.8.0.tar.xz

    - name: install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y cmake libtbb-dev libblas-dev liblapack-dev

    - name: Install Catch
      shell: bash
      run: |
        git clone https://github.com/catchorg/Catch2.git --depth 1
        cd Catch2
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
        cd ..

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DARMADILLO_INCLUDE_DIR="armadillo-12.8.0/include"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
