# Workflow to 
name: CMake on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  tbb_setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update package list and install tbb
        shell: bash
        run: |
          sudo apt update
          sudo apt install libtbb-dev

  arma_setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: dowload armadillo
        shell: bash
        run: |
          wget https://sourceforge.net/projects/arma/files/armadillo-12.8.0.tar.xz
          tar xf armadillo-12.8.0.tar.xz
        env:
          ARMADILLO_INCLUDE_DIRS: "armadillo-12.8.0/include"

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    needs: [tbb_setup, arma_setup]

    steps:
    - uses: actions/checkout@v4

    - name: Summary
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
